name: water_tanker_worker
description: "Water Tanker Delivery Workers App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/user.png
