// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGbPIAsYOgK_ah5h7QSBeCQ4hw1GARfs',
    appId: '1:668038362912:web:6d0117e238fc7898f5c945',
    messagingSenderId: '668038362912',
    projectId: 'water-tanker-delivery-flutter',
    authDomain: 'water-tanker-delivery-flutter.firebaseapp.com',
    storageBucket: 'water-tanker-delivery-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9nLxwlbqvWQRdMak4rRdficfy3W69QQ',
    appId: '1:668038362912:android:408773db686cd822f5c945',
    messagingSenderId: '668038362912',
    projectId: 'water-tanker-delivery-flutter',
    storageBucket: 'water-tanker-delivery-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyLsqZgobHEiQJwICfFAJPUInUngs9ZE',
    appId: '1:668038362912:ios:0e389682906d9468f5c945',
    messagingSenderId: '668038362912',
    projectId: 'water-tanker-delivery-flutter',
    storageBucket: 'water-tanker-delivery-flutter.appspot.com',
    iosClientId: '668038362912-dgenhdvfo4ofhfghjcimc9k02458spp0.apps.googleusercontent.com',
    iosBundleId: 'com.victor.waterTankerWorker',
  );
}
